routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

// Route::get('/login', function () {
//     return view('welcome');
// })->name('login');


// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/load_countries', 'CountriesController@loadCountries')->name('load_countries');

Route::group(['middleware'=> 'auth'], function(){
	Route::resource('pengajuan', 'PengajuanController');
	Route::get('/pengajuan/print/{id}', 'PengajuanController@printSurat')->name('pengajuan.print');
	Route::post('/pengajuan/skm', 'DaftarPengajuanController@skm')->name('pengajuan_skm');
	Route::post('/pengajuan/skdtt', 'DaftarPengajuanController@skdtt')->name('pengajuan_skdtt');
	Route::post('/pengajuan/sku', 'DaftarPengajuanController@sku')->name('pengajuan_sku');
});

Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
	Route::get('/master/warga', 'WargaController@index')->name('warga.index');
	Route::get('/master/warga/{id_pengajuan}/detail', 'WargaController@show')->name('warga.show');
	Route::post('/pengajuan/proses', 'PengajuanController@proses')->name('pengajuan.proses');
	Route::get('/pengajuan/tolak/{id_pengajuan}', 'PengajuanController@tolak')->name('pengajuan.tolak');
	//Pengajuan
});

resources/views/biaya.blade.php
<div class="modal fade" id="modal-biaya">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-red">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Biaya Pengajuan</h4>
		  	</div>
		  	<div class="modal-body">
		        <div class="row">
		        	<div class="col-md-12 table-responsive">
		        		<p>
		        			Pengajuan surat bisa saja dikenakan biaya administrasi, Terima kasih.
		        		</p><br>
		  			</div>
		        </div>
		  	</div>
		    <div class="modal-footer">
		        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
		    </div>
    
    	</div>
  	</div>
</div>

resources/views/dkpk.blade.php
<div class="modal fade" id="modal-daftar-kpk">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-orange">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Daftar Kartu Pencari Kerja</h4>
		  	</div>
		  	<div class="modal-body">
		        <form class="form-horizontal" action="{{ route('pengajuan.store') }}" autocomplete="off" method="post" enctype="multipart/form-data">
		        	<div class="row">
		        		<div class="col-md-12">
		        			{{ csrf_field() }}
                            <div class="form-group col-md-12 form-group-md">

                            	<div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Foto 2 x 3</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="foto" required>
		                                    @if ($errors->has('foto'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('foto') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Scan KTP</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="ktp" required>
		                                    @if ($errors->has('ktp'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('ktp') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Scan Ijazah</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="ijazah" required>
		                                    @if ($errors->has('ijazah'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('ijazah') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Scan Kartu Keluarga</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="kk" required>
		                                    @if ($errors->has('kk'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('kk') }}</strong>
		                                        </span>
		                                    @endif
		                                    <input type="hidden" name="jenis_pengajuan" value="kpk">
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
                            </div>
                            <div class="col-md-12">
                            	<br>
                            	<br>
                            	<br>
                            	<center>
                            		<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
                            		<button class="btn btn-danger" data-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i> Batalkan</button>
                            	</center>
                            </div>
		        		</div>
		        	</div>
		        </form>
		  	</div>
    	</div>
  	</div>
</div>

resources/views/dskaw.blade.php
<div class="modal fade" id="modal-dskaw">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-primary">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Pendaftaran Surat Keterangan Ahli Waris</h4>
		  	</div>
		  	<div class="modal-body">
		        <div class="row">
		        	<div class="col-md-12 table-responsive">
		        		<p>
		        			Pendaftaran untuk Surat Keterangan Ahli Waris ini harus datang langsung ke tempat kantor kami, serta membawa semua dokumen persyaratannya.
		        		</p><br>
		  			</div>
		        </div>
		  	</div>
		    <div class="modal-footer">
		        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
		    </div>
    
    	</div>
  	</div>
</div>

resources/views/dskdtt.blade.php
<div class="modal fade" id="modal-daftar-skdtt">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-orange">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Pengajuan Surat Keterangan Domisili Tempat Tinggal</h4>
		  	</div>
		  	<div class="modal-body">
		        <form class="form-horizontal" action="{{ route('pengajuan_skdtt') }}" autocomplete="off" method="post" enctype="multipart/form-data">
		        	<div class="row">
		        		<div class="col-md-12">
		        			{{ csrf_field() }}
                            <div class="form-group col-md-12 form-group-md">
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Scan KTP</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="ktp" required>
		                                    @if ($errors->has('ktp'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('ktp') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Kartu Keluarga</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="kk" required>
		                                    @if ($errors->has('kk'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('kk') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Surat Pengantar RT/RW</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="spr" required>
		                                    @if ($errors->has('spr'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('spr') }}</strong>
		                                        </span>
		                                    @endif
		                                    <input type="hidden" name="jenis_pengajuan" value="skdtt">
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
                            </div>
                            
                            <div class="col-md-12">
                            	<br>
                            	<br>
                            	<br>
                            	<center>
                            		<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
                            		<button class="btn btn-danger" data-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i> Batalkan</button>
                            	</center>
                            </div>
		        		</div>
		        	</div>
		        </form>
		  	</div>
    	</div>
  	</div>
</div>

resources/views/dskdu.blade.php
<div class="modal fade" id="modal-dskdu">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-primary">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Pendaftaran Surat Keterangan Domisili Usaha</h4>
		  	</div>
		  	<div class="modal-body">
		        <div class="row">
		        	<div class="col-md-12 table-responsive">
		        		<p>
		        			Pendaftaran untuk Surat Keterangan Domisili Usaha ini harus datang langsung ke tempat kantor kami, serta membawa semua dokumen persyaratannya.
		        		</p><br>
		  			</div>
		        </div>
		  	</div>
		    <div class="modal-footer">
		        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
		    </div>
    
    	</div>
  	</div>
</div>

resources/views/dskm.blade.php
<div class="modal fade" id="modal-daftar-skm">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-orange">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Pengajuan Surat Kematian</h4>
		  	</div>
		  	<div class="modal-body">
		        <form class="form-horizontal" action="{{ route('pengajuan_skm') }}" autocomplete="off" method="post" enctype="multipart/form-data">
		        	<div class="row">
		        		<div class="col-md-12">
		        			{{ csrf_field() }}
                            <div class="form-group col-md-12 form-group-md">
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Scan KTP Alm</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="ktp" required>
		                                    @if ($errors->has('ktp'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('ktp') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Kartu Keluarga Alm</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="kk" required>
		                                    @if ($errors->has('kk'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('kk') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Surat Pengantar RT/RW</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="spr" required>
		                                    @if ($errors->has('spr'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('spr') }}</strong>
		                                        </span>
		                                    @endif
		                                    <input type="hidden" name="jenis_pengajuan" value="skm">
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
                            </div>
                            <div class="form-group col-md-12 form-group-md">
                            	<div class="col-md-12">
                            		<label class="control-label col-md-3">Nama Lengkap Alm</label>
                            		<div class="form-group col-md-4">
                            			<input type="text" name="nama_alm" class="form-control">
                            		</div>
                            	</div>
                            	<div class="col-md-12">
                            		<label class="control-label col-md-3">Alamat Lengkap Alm</label>
                            		<div class="form-group col-md-4">
                            			<textarea name="alamat_alm" class="form-control" rows="3"></textarea>
                            		</div>
                            	</div>
                            	<div class="col-md-12">
                            		<label class="control-label col-md-3">Tanggal Meninggal</label>
                            		<div class="form-group col-md-4">
                            			<input type="text" name="tgl_meninggal" class="form-control datepicker">
                            		</div>
                            	</div>
                            </div>
                            <div class="col-md-12">
                            	<br>
                            	<br>
                            	<br>
                            	<center>
                            		<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
                            		<button class="btn btn-danger" data-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i> Batalkan</button>
                            	</center>
                            </div>
		        		</div>
		        	</div>
		        </form>
		  	</div>
    	</div>
  	</div>
</div>

resources/views/dsku.blade.php
<div class="modal fade" id="modal-daftar-sku">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-orange">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Pengajuan Surat Keterangan Usaha</h4>
		  	</div>
		  	<div class="modal-body">
		        <form class="form-horizontal" action="{{ route('pengajuan_sku') }}" autocomplete="off" method="post" enctype="multipart/form-data">
		        	<div class="row">
		        		<div class="col-md-12">
		        			{{ csrf_field() }}
                            <div class="form-group col-md-12 form-group-md">
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Scan KTP</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="ktp" required>
		                                    @if ($errors->has('ktp'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('ktp') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Kartu Keluarga</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="kk" required>
		                                    @if ($errors->has('kk'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('kk') }}</strong>
		                                        </span>
		                                    @endif
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
						        <div class="col-md-3">
						            <!-- Profile Image -->
						            <div class="box box-danger">
						                <div class="box-body box-profile">
						                  	<center><label class="form-control-static">Surat Pengantar RT/RW</label></center>
		                                	<img src="{{ asset('img/bg/img.png') }}" class="img-responsive">
		                                    <input type="file" class="form-control" name="spr" required>
		                                    @if ($errors->has('spr'))
		                                        <span class="help-block">
		                                            <strong>{{ $errors->first('spr') }}</strong>
		                                        </span>
		                                    @endif
		                                    <input type="hidden" name="jenis_pengajuan" value="sku">
						                </div>
						                <!-- /.box-body -->
						            </div>
						        </div>
                            </div>
                            <div class="form-group col-md-12 form-group-md">
                            	<div class="col-md-12">
                            		<label class="control-label col-md-3">Nama Jenis Usaha</label>
                            		<div class="form-group col-md-4">
                            			<input type="text" name="nama_alm" class="form-control">
                            		</div>
                            	</div>
                            	<div class="col-md-12">
                            		<label class="control-label col-md-3">Alamat Lengkap</label>
                            		<div class="form-group col-md-4">
                            			<textarea name="alamat_alm" class="form-control" rows="3"></textarea>
                            		</div>
                            	</div>
                            </div>
                            <div class="col-md-12">
                            	<br>
                            	<br>
                            	<br>
                            	<center>
                            		<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
                            		<button class="btn btn-danger" data-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i> Batalkan</button>
                            	</center>
                            </div>
		        		</div>
		        	</div>
		        </form>
		  	</div>
    	</div>
  	</div>
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kpk.blade.php
<div class="modal fade" id="modal-kpk">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-primary">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Persyaratan Kartu Pencari Kerja</h4>
		  	</div>
		  	<div class="modal-body">
		        <div class="row">
		        	<div class="col-md-12 table-responsive">
		        		<p>
		        			Kartu yang diisyaratkan untuk mendapatkan pekerjaan serta mendata tingkat pengangguran. Kartu ini hanya berlaku 6 bulan saja.
		        		</p><br>
		        		<table class="table table-condensed table-hover table-striped table-bordered">
		        			<thead>
		        				<tr>
		        					<th width="5%" class="text-right">No.</th>
		        					<th width="15%" class="text-center">Ketentuan</th>
		        					<th>Syarat</th>
		        				</tr>
		        			</thead>
		        			<tbody>
		        				<tr>
		        					<td class="text-right">1.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Pas Foto 2x3 cm 2 lembar</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">2.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Scan KTP</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">3.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Scan Ijazah</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">4.</td>
		        					<td class="text-center">Tidak Wajib</td>
		        					<td>Scan Kartu Keluarga (KK)</td>
		        				</tr>
		        			</tbody>
		        		</table>
		  			</div>
		        </div>
		  	</div>
		    <div class="modal-footer">
		        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
		    </div>
    
    	</div>
  	</div>
</div>

resources/views/skaw.blade.php
<div class="modal fade" id="modal-skaw">
  	<div class="modal-dialog">
        <div class="modal-content">
		  	<div class="modal-header bg-primary">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      		<span aria-hidden="true">&times;</span>
		  		</button>
		    	<h4 class="modal-title">Persyaratan Surat Keterangan Domisili Usaha</h4>
		  	</div>
		  	<div class="modal-body">
		        <div class="row">
		        	<div class="col-md-12 table-responsive">
		        		<p>
		        			Surat Keterangan Ahli Waris atau Surat Keterangan Waris (SKW) adalah surat yang dibutuhkan untuk melengkapi persyaratan atau kelengkapan administratif dalam urusan tertentu. Pengurusan ini dilakukan di Kelurahan lalu melanjutkan ke Kecamatan. 
		        		</p><br>
		        		<table class="table table-condensed table-hover table-striped table-bordered">
		        			<thead>
		        				<tr>
		        					<th width="5%" class="text-right">No.</th>
		        					<th width="15%" class="text-center">Ketentuan</th>
		        					<th>Syarat</th>
		        				</tr>
		        			</thead>
		        			<tbody>
		        				<tr>
		        					<td class="text-right">1.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Surat Pengantar RT/RW</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">2.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Surat Pernyataan Ahli Waris</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">3.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>KK Pewaris</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">4.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>KTP Pewaris</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">5.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Surat Pencatatan Sipil Akta Kematian</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">6.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Akta Lahir Ahli Waris yang belum cukup umur</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">7.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Surat Keterangan Kematian dari Kelurahan</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">8.</td>
		        					<td class="text-center">Wajib</td>
		        					<td>Surat Nikah</td>
		        				</tr>
		        				<tr>
		        					<td class="text-right">9.</td>
		        					<td class="text-center">Tidak Wajib</td>
		        					<td>KTP masing-masing Ahli Waris</td>
		        				</tr>
		        			</tbody>
		        		</table>
		  			</div>
		        </div>
		  	</div>
		    <div class="modal-footer">
		        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
		    </div>
    
    	</div>
  	</div>
</div>