routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

// Route::get('/login', function () {
//     return view('welcome');
// })->name('login');


// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/load_countries', 'CountriesController@loadCountries')->name('load_countries');

Route::group(['middleware'=> 'auth'], function(){
	Route::resource('pengajuan', 'PengajuanController');
	Route::get('/pengajuan/print/{id}', 'PengajuanController@printSurat')->name('pengajuan.print');
	Route::post('/pengajuan/skm', 'DaftarPengajuanController@skm')->name('pengajuan_skm');
	Route::post('/pengajuan/skdtt', 'DaftarPengajuanController@skdtt')->name('pengajuan_skdtt');
	Route::post('/pengajuan/sku', 'DaftarPengajuanController@sku')->name('pengajuan_sku');
});

Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
	Route::get('/master/warga', 'WargaController@index')->name('warga.index');
	Route::get('/master/warga/{id_pengajuan}/detail', 'WargaController@show')->name('warga.show');
	Route::post('/pengajuan/proses', 'PengajuanController@proses')->name('pengajuan.proses');
	Route::get('/pengajuan/tolak/{id_pengajuan}', 'PengajuanController@tolak')->name('pengajuan.tolak');
	//Pengajuan
});

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>LPM</title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('/bower_components/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('/bower_components/Ionicons/css/ionicons.min.css') }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('/bower_components/select2/dist/css/select2.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('/dist/css/skins/_all-skins.min.css') }}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/custom.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/toastr.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/paper.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('/plugins/iCheck/all.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <style type="text/css">
        .modal .modal-dialog{
            width: 80%;
        }
    </style>
    @yield('style')
</head>
<body class="hold-transition skin-purple-light layout-top-nav">
    <div class="wrapper">
        <header class="main-header">
            <nav class="navbar navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <a href="{{ route('welcome') }}" class="navbar-brand"><b>BERANDA</b></a>
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <!-- Navbar Right Menu -->
                    <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
                        <ul class="nav navbar-nav">
                            @if (Auth::guest())
                                <li><a href="#">Tentang</a></li>
                                <li><a href="#">FAQ</a></li>
                                <li><a href="{{ route('login') }}">Login</a></li>
                                <li><a href="{{ route('register') }}">Registrasi</a></li>
                            @else
                                @role('admin')
                                    <li><a href="{{ route('warga.index') }}">Warga</a></li>
                                    <li><a href="{{ route('pengajuan.index') }}">Daftar Pengajuan</a></li>
                                @endrole
                                @role('warga')
                                    <li><a href="{{ route('pengajuan.index') }}">Pengajuan Saya</a></li>
                                @endrole
                                <li>
                                    <a href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            @endif
                            <li>
                                <img src="{{ asset('img/logo/riste.jpeg') }}" height="50px;">
                            </li>
                            <li>
                                <img src="{{ asset('img/logo/amik.jpeg') }}" height="50px;">
                            </li>
                            <li>
                                <img src="{{ asset('img/logo/kbb.jpeg') }}" height="50px;">
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-custom-menu -->
                </div>
                <!-- /.container-fluid -->
            </nav>
        </header>
        <!-- Full Width Column -->
        <div class="content-wrapper">
            <div class="container">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <!-- Jenis Pelayanan Masyarakt -->
                        <!-- <small>Example 2.0</small> -->
                    </h1>
                    
                </section>

                <!-- Main content -->
                <section class="content">
                    @include('layouts._flash_notification')
                    @yield('content')
                </section>

                        <!-- /.content -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0.0
                </div>
                <strong>Copyright &copy; 2019</strong>
            </div>
            <!-- /.container -->
        </footer>
    </div>
    

    <!-- jQuery 3 -->
    <script src="{{ asset('/bower_components/jquery/dist/jquery.min.js') }}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{{ asset('/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{{ asset('/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- DataTables -->
    <script src="{{ asset('/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ asset('/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    
    <!-- daterangepicker -->
    <script src="{{ asset('/bower_components/moment/min/moment.min.js') }}"></script>
    <script src="{{ asset('/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <!-- datepicker -->
    <script src="{{ asset('/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <!-- Slimscroll -->
    <script src="{{ asset('/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('/bower_components/fastclick/lib/fastclick.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('/dist/js/adminlte.min.js') }}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <!-- <script src="{{ asset('/dist/js/pages/dashboard.js') }}"></script> -->
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('/js/set_url_active.js') }}"></script>
    <!-- Select2 -->
    <script src="{{ asset('/bower_components/select2/dist/js/select2.min.js') }}"></script>
    <!-- toastr -->
    <script src="{{ asset('/js/toastr.min.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('/plugins/iCheck/icheck.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass   : 'iradio_minimal-blue'
            })
        });
        $(function () {

            //load select2
            $('.loadCountries').select2({
                placeholder: "Pilih Salah Satu",
                ajax: {
                    url: "{{ url('/load_countries') }}",
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            q: $.trim(params.term)
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };
                    },
                    cache: true
                }
            });

            //load select2
            $('.select-option').select2({
                placeholder: "Pilih Salah Satu",
            });

            //***** number
            $('input.number').on('change keyup', function() {
                // skip for arrow keys
                if(event.which >= 37 && event.which <= 40) return;

                // format number
                $(this).val(function(index, value) {
                    return value
                    .replace(/\D/g, "")
                    .replace(/([0-9])([0-9]{2})$/, '$1$2');
                });
            });

            //Date picker
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd',
                autoclose:true,
                showOnFocus:true,
              
            })

            $('#example1').DataTable({
              // 'paging'      : true,
              // 'lengthChange': false,
              // 'searching'   : true,
              // 'ordering'    : true,
              // 'info'        : true,
              // 'autoWidth'   : true
            })
        });
    </script>

    @yield('javascript')

</body>
</html>

resources/views/templates/print_slip.blade.php
<html>
<head>
    <link rel="stylesheet" href="{{ asset('/css/custom.css') }}">
    <title>Print</title>
    <style>
    @media print {  
      @page { size: A4;
         margin:1cm;
       }
      .sheet {
        overflow: visible;
        height: auto !important;
        page-break-inside:avoid; page-break-after:auto;
        page-break-before: always;
      }


      h1 {
        font-size: 12pt;
        margin-bottom: 4px;
      }
    }

    @media screen{
      @page { size: A4; margin:1cm !important; }
      .sheet {
        overflow: visible;
        height: auto !important;
        page-break-inside:avoid; page-break-after:auto;
        page-break-before: always;
        padding-left:6cm;
        padding-top:1cm;
        padding-right:6cm;
      }

      h1 {
        font-size: 12pt;
        margin-bottom: 4px;
      }
    }
    
    body {
        font-family: Trebuchet MS,Arial;
        font-size: 12px;
    }

    </style>
</head>

<body class="A4">
  <section class="sheet">
    @yield('content')
  </section>
</body>
<script src="{{ asset('/bower_components/jquery/dist/jquery.min.js') }}"></script>
<script type="text/javascript">
    $(function () {
        // printInvoice();
    });
    
    function printInvoice() {
        window.print();
    }
  </script>
</html>